# Generated by Django 4.1.5 on 2023-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('geography', 'Geography'), ('entertainment', 'Entertainment'), ('history', 'History'), ('literature', 'Art & Literature'), ('science', 'Science & Nature'), ('sports', 'Sports & Leisure')], max_length=32),
        ),
    ]
